/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OpaleAccordion {
        "color": string;
        "description": string;
        "label": string;
        "width": string;
    }
}
declare global {
    interface HTMLOpaleAccordionElement extends Components.OpaleAccordion, HTMLStencilElement {
    }
    var HTMLOpaleAccordionElement: {
        prototype: HTMLOpaleAccordionElement;
        new (): HTMLOpaleAccordionElement;
    };
    interface HTMLElementTagNameMap {
        "opale-accordion": HTMLOpaleAccordionElement;
    }
}
declare namespace LocalJSX {
    interface OpaleAccordion {
        "color"?: string;
        "description"?: string;
        "label"?: string;
        "on$toggle"?: (event: CustomEvent<any>) => void;
        "width"?: string;
    }
    interface IntrinsicElements {
        "opale-accordion": OpaleAccordion;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "opale-accordion": LocalJSX.OpaleAccordion & JSXBase.HTMLAttributes<HTMLOpaleAccordionElement>;
        }
    }
}
